version: '2'
services:
  web:
    build: ./web
    ports:
      - "5000:80"
    volumes:
      - ./web:/web
    depends_on:
      - atlas_visualisation

  atlas_visualisation:
    build: ./atlas_visualisation
    volumes:
      - ./atlas_visualisation:/atlas_visualisation
    ports:
      - "5006:5006"


