version: '3'
services:
  web:
    build: ./web
    ports:
      - "19878:80"
    volumes:
      - ./web:/web
    depends_on:
      - atlas_visualisation

  atlas_visualisation:
    build: ./atlas_visualisation
    volumes:
      - ./atlas_visualisation:/atlas_visualisation
    ports:
      - "5006:5006"


